<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_init()
 */
function commerce_reports_bysource_init(){

	$request = Request::createFromGlobals();

    $src_tmp = $request->query->get('src');
    if ( !empty($src_tmp) ){
            if ( !isset($_SESSION['commerce_reports_bysource']['src_code']) || empty($_SESSION['commerce_reports_bysource']['src_code']) ){
                    $_SESSION['commerce_reports_bysource']['src_code'] = $src_tmp;
            }
    }

}

/**
 * Action for rule commerce_reports_bysource_classify
 */
function commerce_reports_bysource_classify_order($order){

	//set values
	unset($term);
	if ( array_key_exists('commerce_reports_bysource', $_SESSION) && array_key_exists('src_code', $_SESSION['commerce_reports_bysource']) ) {
		
		$src_code = $_SESSION['commerce_reports_bysource']['src_code'];
	
		$vocabulary = 'commerce_reports_bysource';
		$vocabulary_names = taxonomy_vocabulary_get_names();
		$vid = $vocabulary_names[$vocabulary]->vid;
		$tid = taxonomy_get_term_by_name($src_code, $vocabulary);

		//if not exists source create it
		if (empty($tid)){
			$newsrc = (object) array(
				'name' => $src_code,
				'description' => 'Source: ' . $src_code,
				'vid' => $vid,
				);
			taxonomy_term_save($newsrc);
			$tid = $newsrc->tid;
		}

		//if not arte instance $order do it
		if (!($order instanceof EntityMetadataWrapper)) {
	    	$order = entity_metadata_wrapper('commerce_order', $order);
	  	}

	  	//classify order by source and save
	  	$order->field_data_field_reports_bysource['und'][0]['field_reports_bysource_tid'] = $tid;
	  	commerce_order_save($order);

	  	$results = array(
	  		'tid' => $tid,
	  		'field' => $order->field_data_field_reports_bysource['und'][0]['field_reports_bysource_tid'],
	  		'order' => $order
	  		);
	  	drupal_set_message("<pre>" . print_r($results, 1) . "</pre>");

	  	unset($_SESSION['commerce_reports_bysource']['src_code']);
  	}

}

/**
 * Implements hook_views_api().
 */
function commerce_reports_bysource_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_reports_bysource') . '/views',
  );
}
